### ISSUE TITLE
Use case - member directory with search

### ISSUE THREAD

**Issue by KarlHRichter** [interop-alliance/life-server#56]
This is a high level tracking ticket for the overall use case for using my server as a member directory with the ability to search member profiles.

**Comment by dmitrizagidulin** [comment]
Depends on:
* [ ] [#57 - Protect/authenticate account creation API endpoint](https://github.com/interop-alliance/life-server/issues/57)
* [ ] [#58 - Implement a List Accounts admin API endpoint](https://github.com/interop-alliance/life-server/issues/58)
* [ ] [#59 - Specify schema/vocab/shape tree for a public user profile](https://github.com/interop-alliance/life-server/issues/59)
